### ISSUE TITLE
Format for 'myPrivateKey' in Example

### ISSUE THREAD

**Issue by Klar** [libitx/txforge#19]
Which Format must the 'myPrivateKey' be in the example forge Transaction?

I'm currently trying with bsv v2: _const privKey = bsv.PrivKey.fromWif(myPrivateKey)_  but it does not work.

Maybe you could add a "real" privateKey as an example.

**Comment by libitx** [comment]
TxForge >= 2.0 uses nimble not bsv2, so it would be `nimble.PrivateKey.fromString(wif)`

If you don't want to use nimble, TxForge legacy uses bsv2 so it would be as you expect (although minor api differences in txforge so make sure you refer to the [legacy branch readme](https://github.com/libitx/txforge/tree/legacy).
