### ISSUE TITLE
Unable to Solve this --> SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jsim77** [libitx/txforge#20]

**Comment by libitx** [comment]
Either ensure your project is an ESM module by putting `"module": true`  in `package.json` or don't use import statements, swap `import { forgeTx } from 'txforge'` to `const { forgeTx } = require('txforge')`.

**Comment by jsim77** [comment]
@libitx - My apology for the late reply and Yes! is working, thanks
