### ISSUE TITLE
Throw helpful error when wrong version of bsv is required within txforge

### ISSUE THREAD

**Issue by shruggr** [libitx/txforge#3]
TypeError: Cannot read property 'OP_RETURN' of undefined at Object.<anonymous> (/workspace/node_modules/txforge/dist/txforge.cjs.js:354:18) at Module._compile (internal/modules/cjs/loader.js:1133:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10) at Module.load (internal/modules/cjs/loader.js:977:32) at Function.Module._load (internal/modules/cjs/loader.js:877:14) at Module.require (internal/modules/cjs/loader.js:1019:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.<anonymous> (/workspace/hybrid-server.js:35:19) at Module._compile (internal/modules/cjs/loader.js:1133:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

npm version 0.1.7

**Comment by libitx** [comment]
Seems the issue was related to the wrong version of bsv being required.

I'm gonna keep this issue open as a reminder to handle this with some kind of helpful error message as I don't think you'll be the last to do this :)
