### ISSUE TITLE
Review fee calculation logic

### ISSUE THREAD

**Issue by libitx** [libitx/txforge#5]
Reports that sometimes the fee gets calculated at 0.499 s/b. Review the fee calculation logic.
Possibly the feeEstimate function is just wrong. Possibly the p2pkh input size is wrong (check sig size).

**Comment by sirdeggen** [comment]
If others make the same mistake I did, then it's just a float rounding error, fixed by adding 

```return Math.ceil(size)```

To the end of your size function in the locking and unlocking script of custom Casts.

Cheers,

- Deggen
