### ISSUE TITLE
Transaction Version Number

### ISSUE THREAD

**Issue by sirdeggen** [libitx/txforge#6]
Sometimes TxForge creates transactions which have their version byte set to 00 rather than 01.

I cannot figure out why (so far).

**Comment by sirdeggen** [comment]
Further investigation reveals that at some point it is being replaced with nLocktime. When inspecting the object after adding inputs and signing:

`versionBytesNum: {nLockTime: undefined}`

**Comment by libitx** [comment]
Thanks for reporting this @sirdeggen I may have inadvertantly introduced this with the latest release which enabled setting nlocktime on the txforge instance.

If its causing issues, revert to version 0.1.7 whilst I dig in to this.

**Comment by libitx** [comment]
This is fixed now. Please upgrade to version 0.1.10.
